[package]
name = "retch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hostname = "0.3.1"
itertools = "0.14.0"
sysinfo = "0.30.7"
